pytorch/captum

captum/attr/_core/neuron_conductance.py
captum/attr/_utils/common.py
captum/attr/_utils/gradient.py
sphinx/source/common.rst
tests/attr/test_neuron_gradient.py

Switching to suggested new approach for indexing neurons with arbitrary length tuples as opposed to an iterated select.

Fixing Neuron Indexing

---

captum/attr/_core/deep_lift.py
tests/attr/helpers/basic_models.py
tests/attr/test_deeplift_basic.py

Currently, the deeplift multiplier gets replaced with the normal gradient if `delta_in` is smaller than epsilon - this means any negative values get replaced.
This PR only replaces the gradient if the absolute value of `delta_in` is smaller than `epsilon`, and adds a test which failed before the change.
Thanks!

Only replace the deeplift multiplier if the absolute value of delta_in is small

---

captum/attr/_core/deep_lift.py
captum/attr/_core/gradient_shap.py
captum/attr/_utils/common.py
tests/attr/test_deeplift_basic.py
tests/attr/test_gradient_shap.py

Expanding supported data types for `baselines` and adding callable function in addition to torch.Tensor and a tuple of torch.Tensor-s.
1. Adding support of baselines as a functions for DeepLiftShap and GradientShap, however we can 
potentially expand it and  add support for all methods that take baselines.
2. We can potentially combine `_format_callable_baseline` and `format_baseline`  but since other 
algorithms do not support callable baseline I created a separate function and will potentially 
combine it with `format_baseline`

Support baselines as a function for DeepLift SHAP and Gradient SHAP

---

website/pages/tutorials/index.js

Fixing website link to Getting Started tutorial rather than PyTorch tutorial (issue: 128).

Fixing Getting Started Link

---

captum/insights/api.py

Addresses issues in Insights:
#133 -> Fixes additional_forward_args argument, which was incorrectly being passed as target.
#129 -> Adding port as argument to render. We can also add this as a command line argument to example.py, but this should make it easy to specify a port for custom applications.

Fixing Additional Args Bug and Port

---

captum/attr/_utils/common.py
captum/insights/api.py
captum/insights/features.py

- if attribution vector == 0, L2 and L-infinity norm will be zero
- removed Optional annotation from `TextFeature`'s `visualization_transform` since it is required

fix division by zero in captum/insights/features.py

---

.circleci/config.yml

This roughly reverts https://github.com/pytorch/captum/commit/d327a247f3b7e52e160e725910fdd45872681505
and makes it so the captum.ai website is automatically updated when changes land in master.
cc @jlin27 @caraya10 @NarineK @vivekmig

Add back auto_deploy_site for CircleCI master

---

.circleci/config.yml

This now uses `diff`  instead of `diff-tree` that didn't seem to be working. Looks like botorch has moved on from this check in their repository, so seems like a reasonable change for us. Need to land to master to confirm.

Simplify website build deployment check

---

website/core/Footer.js

For "reasons", we don't actually have a CNAME set up in GitHub. The
result is that GitHub doesn't know that pytorch.org/captum should
actually redirect to captum.ai. This change puts a bit of JS on every
page in prod that will do that redirect. We should fix it properly but
at least we'll have something in place.

Redirect website to real root domain

---

scripts/versions.js
website/core/Footer.js
website/core/Tutorial.js
website/core/TutorialSidebar.js
website/pages/en/index.js
website/pages/tutorials/index.js
website/siteConfig.js

We had MIT in here before. Really an excuse to test the website update.

Match BSD license in JS files

---

captum/attr/_core/deep_lift.py
captum/attr/_core/grad_cam.py
captum/attr/_core/guided_grad_cam.py
captum/attr/_core/internal_influence.py
captum/attr/_core/layer_activation.py
captum/attr/_core/layer_conductance.py
captum/attr/_core/layer_deep_lift.py
captum/attr/_core/layer_gradient_x_activation.py
captum/attr/_core/neuron_conductance.py
captum/attr/_core/neuron_deep_lift.py
captum/attr/_core/neuron_gradient.py
captum/attr/_core/neuron_guided_backprop_deconvnet.py
captum/attr/_core/neuron_integrated_gradients.py
captum/attr/_utils/gradient.py
tests/attr/helpers/basic_models.py
tests/attr/helpers/utils.py
tests/attr/test_data_parallel.py
tests/attr/test_layer_deeplift_basic.py
tests/attr/test_neuron_deeplift_basic.py

1. Adds an option to attribute to neuron or layer inputs. Originally, we were attributing only to the outputs but we can also attribute to the inputs.
2. Adds separate implementation for NeuronDeepLift and LayerDeepLift.
3. Parallelization with `DataParallel` for DeepLift isn't trivial due to internal replication of the modules,  we'll need to override some parts of it but since this diff is already very large, I'm not doing it here ...
Currently, it accesses to internal module of `DataParallel` in case it is wrapped with `DataParallel` 
Fixes issue https://github.com/pytorch/captum/issues/91

Add support for attributing to layer and neuron inputs and DeepLift layer and neuron

---

captum/concept/__init__.py

The internal and external repositories are out of sync. This attempts to brings them back in sync by patching the GitHub repository. Please carefully review this patch. You must disable ShipIt for your project in order to merge this pull request. DO NOT IMPORT this pull request. Instead, merge it directly on GitHub using the MERGE BUTTON. Re-enable ShipIt after merging.

Re-sync with internal repository

---

captum/optim/_models/inception_v1.py
tests/optim/models/test_models.py

This PR doesn't overlap with any other PRs. We don't need a RGB to BGR transform inside the model. Currently InceptionV1 is optimizing images in RGB instead of BGR, which results in really bluish visualization images. Visualization results should now match the colors found on OpenAI Microscope: https://microscope.openai.com/models/inceptionv1/mixed4c_0/?models.op.feature_vis.type=channel&models.op.technique=feature_vis
Ludwig's model had the RGB to BGR transform commented out here as well: https://github.com/ludwigschubert/captum/blob/f1fd0729dece59564a7c10b7b397617d8a09a247/captum/optim/models/inception_v1.py#L200-L209
* I made the InceptionV1 model's internal BGR transform optional. By default it's set to False.

Optim wip: Fix InceptionV1 color space

---

captum/optim/_utils/circuits.py
tutorials/optimviz/WeightVisualization_OptimViz.ipynb

* Fixed the link in `extract_expanded_weights` so that it now correctly points to the research article: https://distill.pub/2020/circuits/visualizing-weights/
* Corrected the first author name to be Chelsea Voss (@csvoss) in the `extract_expanded_weights` citation.
Should I also add a link to the article in the notebook?

Optim-wip: Correct weight visualization citation

---

captum/attr/_core/feature_ablation.py
captum/metrics/_core/infidelity.py
captum/optim/__init__.py
captum/optim/_core/optimization.py
captum/optim/_param/image/images.py
captum/optim/_param/image/transforms.py
captum/optim/models/__init__.py
captum/optim/models/_common.py
captum/optim/models/_image/inception_v1.py
scripts/install_via_conda.sh
tests/optim/core/test_optimization.py
tests/optim/helpers/numpy_image.py
tests/optim/models/test_models_common.py
tests/optim/param/test_images.py
tests/optim/param/test_transforms.py
tests/optim/utils/test_reducer.py

* Quick fix for the model file path as it's breaking all the notebooks & tests.
* It also looks like `black` was updated and now is reporting an issue with `captum/attr/_core/feature_ablation.py` &  `captum/metrics/_core/infidelity.py`, so I've resolved that as well. The files in the master branch may be a bit different, but we need to at least keep the tests passing for the other areas of Captum until we merge into master.
* Added new `ImageTensor` tests.
* Added `detach()` to `InputOptimization` to fix out of memory crashes.
* Made sure that `SkipLayer` can handle any addition arguments to it's init and forward functions. This adds to the usefulness of the layer and improves it beyond just copying `nn.Identity`.
* Fixed various bugs.

Optim-wip: Fix failing tests, model download link, & more

---

captum/optim/models/_common.py
tests/optim/models/test_models_common.py
tutorials/optimviz/atlas/ActivationAtlasSampleCollection_OptimViz.ipynb

Refer to #579 for more details, this PR replaces #729
This PR adds the setup tutorial notebook for collecting the required sample activations and attributions for activation atlases from user supplied image datasets.
It also adds the required relaxed max pooling layer used to collect sample attributions. This layer was included in `captum/optim/models/_common.py`, so we can verify it works correctly for the tutorial.
For some reason Github thinks I changed the entire `captum/optim/models/_common.py`, when all I did was add the `Optional` type hint and the `MaxPool2dRelaxed` class at the bottom of the file.

Optim-wip: Add Activation Atlas sample collection tutorial & supporting code

---

captum/optim/__init__.py
captum/optim/_core/loss.py
captum/optim/_param/image/transforms.py
captum/optim/_utils/atlas.py
captum/optim/_utils/image/atlas.py
captum/optim/_utils/image/common.py
tests/optim/core/test_loss.py
tests/optim/helpers/numpy_transforms.py
tests/optim/param/test_transforms.py
tests/optim/utils/image/common.py
tests/optim/utils/image/test_atlas.py
tests/optim/utils/test_atlas.py

This PR simplifies the commit history of https://github.com/pytorch/captum/pull/579

Optim-wip: Add main Activation Atlas tutorial & functions

---

website/pages/en/index.js

Here at Meta Open Source, we've been creating short-form videos to explain Meta OSS projects in the simplest terms possible. We started embedding these videos into project pages as you can see in [Docusaurus home page](https://docusaurus.io/), [Jest](https://jestjs.io/), [Litho](https://fblitho.com/), [Hydra](https://hydra.cc/), etc..
Here is a screenshot in how it looks:

Adding Explain Like I'm 5 video to the home page

---

tests/optim/helpers/models.py
tests/optim/models/test_inceptionv1.py

This change will make it easier to use these helpers for testing other models.

Optim-wip: Move inception test helpers to separate file

---

captum/optim/models/_common.py

There was an issue where multiple separators were not used, and thus a layer like: `layer4[5].relu3` was incorrectly listed as `layer4.[5].relu3` (with a period between the list index and the module name, rather than no separator).

Optim-wip: Fix issue with `get_model_layers`

---

captum/optim/_core/loss.py
captum/optim/_core/optimization.py
captum/optim/models/_common.py

Some PyTorch modules that can be used as targets have an `__iter__` attribute, like `torch.nn.Sequential`. The current target system only checks for the `__iter__` attribute to determine if a target is already in a list or not, and thus doesn't work with targets like Sequential modules. This PR fixes this bug.
This PR also corrects `InputOptimization`'s model variable type hint to reflect the fact that it's optional.

Optim-wip: Fix bug with nn.Sequential targets

---

captum/optim/_param/image/images.py
captum/optim/_param/image/transforms.py
captum/optim/_utils/image/common.py
captum/optim/_utils/typing.py
tests/optim/helpers/numpy_transforms.py
tests/optim/param/test_images.py
tests/optim/param/test_transforms.py

* Added JIT support to all transforms.
* Added JIT tests for all applicable transforms.
* There's currently a bug that prevents `CenterCrop` from working with JIT, so I added the `@torch.jit.ignore` decorator to it's forward function to avoid the bug. This is so that it won't throw an error if someone uses `torch.jit.script` on it. https://github.com/pytorch/pytorch/issues/69938 
* JIT is also told to ignore `NChannelsToRGB` due to it's unsupported inner functions.
* The `ToRGB` didn't support JIT due to the usage of named dimensions, so I implemented a second forward function that is only used when using JIT.
* Add JIT support `NaturalImage`, `FFTImage`, & `PixelImage`.
* Improved `NaturalImage` & `FFTImage` tests, and test coverage.
* Added `ImageParameterization` instance support for …

Optim-wip: Add JIT support to all transforms & some image parameterizations

---

captum/optim/models/_image/inception_v1.py

Not removing the actual file yet as other PRs are still using the GitHub link.

Optim-wip: Change Inception5h model link
